/**
 * Shared color constants for the UNILUME app.
 *
 * Brand color: #e2740e
 * Palette generated by antd 6 @ant-design/colors algorithm.
 * Keep in sync with AntdProvider theme tokens.
 */

/** Brand orange — 10-level palette generated from seed #e2740e */
export const BRAND = {
  1: "#fff7ed",
  2: "#ffedd5",
  3: "#fed7aa",
  4: "#fdba74",
  5: "#fb923c",
  6: "#e2740e",
  7: "#c55a00",
  8: "#9a3412",
  9: "#7c2d12",
  10: "#431407",
} as const;

/** Semantic status colors — matching antd seed tokens */
export const STATUS = {
  success: { bg: "#e1faed", text: "#069469", border: "#80e0b7" },
  warning: { bg: "#fffae6", text: "#cf7c00", border: "#ffde85" },
  error: { bg: "#fff2f0", text: "#c92e34", border: "#ffc8c2" },
  info: { bg: BRAND[1], text: BRAND[6], border: BRAND[3] },
} as const;

/** Chart palette — 8 colors, ordered by distinctiveness */
export const CHART_COLORS = [
  "#e2740e",
  "#10b981",
  "#2563eb",
  "#ef4444",
  "#06b6d4",
  "#8b5cf6",
  "#ec4899",
  "#6b7280",
] as const;

/** Market identifiers — use flag emoji, not color coding */
export const MARKETS = {
  UAE: { flag: "🇦🇪", label: "UAE", currency: "AED" },
  KSA: { flag: "🇸🇦", label: "KSA", currency: "SAR" },
  Egypt: { flag: "🇪🇬", label: "Egypt", currency: "EGP" },
} as const;
