/**
 * Shared color constants for the UNILUME app.
 *
 * Brand color: #533afd
 * Palette generated by antd 6 @ant-design/colors algorithm.
 * Keep in sync with AntdProvider theme tokens.
 */

/** Brand purple — 10-level palette generated from seed #533afd */
export const BRAND = {
  1: "#f4f0ff",
  2: "#e7deff",
  3: "#c6b5ff",
  4: "#a38cff",
  5: "#7d63ff",
  6: "#533afd",
  7: "#3827d6",
  8: "#2117b0",
  9: "#0f0b8a",
  10: "#070763",
} as const;

/** Semantic status colors — matching antd seed tokens */
export const STATUS = {
  success: { bg: "#e1faed", text: "#069469", border: "#80e0b7" },
  warning: { bg: "#fffae6", text: "#cf7c00", border: "#ffde85" },
  error: { bg: "#fff2f0", text: "#c92e34", border: "#ffc8c2" },
  info: { bg: BRAND[1], text: BRAND[6], border: BRAND[3] },
} as const;

/** Chart palette — 8 colors, ordered by distinctiveness */
export const CHART_COLORS = [
  "#533afd",
  "#10b981",
  "#f59e0b",
  "#ef4444",
  "#06b6d4",
  "#8b5cf6",
  "#ec4899",
  "#6b7280",
] as const;

/** Market identifiers — use flag emoji, not color coding */
export const MARKETS = {
  UAE: { flag: "🇦🇪", label: "UAE", currency: "AED" },
  KSA: { flag: "🇸🇦", label: "KSA", currency: "SAR" },
  Egypt: { flag: "🇪🇬", label: "Egypt", currency: "EGP" },
} as const;
